os:
  - linux
  #- osx
  #- windows
jobs:
  include:  # https://docs.travis-ci.com/user/languages
    # | language:    | os: linux       | os: osx         | os: windows     | linux: python3 --version  |
    # | ------------ | --------------- | --------------- | --------------- |                           |
    - language: android      # |                 |                 | NEVER STARTS    | Python 3.4.3 with no pip3 |
    - language: c            # |                 |                 |                 | Python 3.5.2 with no pip3 |
    - language: csharp       # |                 |                 | FAILS           | Python 3.5.2 with no pip3 |
    - language: cpp          # |                 |                 |                 | Python 3.5.2 with no pip3 |
    - language: clojure      # |                 |                 | NEVER STARTS    | Python 3.5.2 with no pip3 |
    - language: crystal      # |                 |                 | FAILS           | Python 3.5.2 with no pip3 |
    - language: d            # |                 |                 | FAILS           | Python 3.5.2 with no pip3 |
    - language: dart         # |                 |                 |                 | Python 3.5.2 with no pip3 |
    - language: elixir       # |                 | FAILS           | FAILS           | Python 3.5.2 with no pip3 |
    - language: elm          # |                 |                 | NEVER STARTS    | Python 3.4.3 with no pip3 |
    - language: erlang       # | FAILS           | FAILS           | FAILS           |                           |
    - language: generic      # | no language set | no language set | FAILS           | Python 3.5.2 with no pip3 |
    - language: go           # |                 |                 |                 | Python 3.5.2 with no pip3 |
    - language: groovy       # | no language set | no language set | FAILS           | Python 3.5.2 with no pip3 |
    - language: haskell      # |                 | FAILS           | FAILS           | Python 3.5.2 with no pip3 |
    - language: haxe         # |                 |                 | FAILS           | Python 3.5.2 with no pip3 |
    - language: java         # |                 |                 | FAILS           | Python 3.5.2 with no pip3 |
    - language: julia        # |                 |                 |                 | Python 3.5.2 with no pip3 |
    - language: minimal      # | no language set | no language set | NEVER STARTS    | Python 3.5.2 with no pip3 |
    - language: nix          # |                 |                 | NEVER STARTS    | Python 3.5.2 with no pip3 |
    - language: node_js      # |                 |                 |                 | Python 3. with no pip3    |
    - language: objective-c  # | Runs on macOS!! | no language set | no language set | Python 3.6.5, pip3 10.0.1 |
    - language: perl         # |                 |                 | FAILS           | Python 3.5.2 with no pip3 |
    - language: perl6        # |                 |                 |                 | Python 3.5.2 with no pip3 |
    - language: php          # |                 | FAILS           | FAILS           | Python 3.5.2 with no pip3 |
    - language: python       # |                 | FAILS           | FAILS           | language: python: 3.8 pip |
    - language: r            # |                 |                 | FAILS           | Python 3.5.2 with no pip3 |
    - language: ruby         # |                 |                 | FAILS           | Python 3.5.2 with no pip3 |
    - language: rust         # |                 |                 |                 | Python 3.5.2 with no pip3 |
    - language: scala        # |                 |                 | FAILS           | Python 3.5.2 with no pip3 |
    - language: smalltalk    # |                 |                 | NEVER STARTS    | Python 3.4.3 with no pip3 |

install: true
script:
  - python         --version || true
  - python2        --version || true
  - python3        --version || true
  - python  -m pip --version || true
  - python2 -m pip --version || true
  - python3 -m pip --version || true
  - pyenv version            || true
  - pyenv whence python3     || true
  - pyenv whence pip         || true
  - pyenv versions           || true
  - pyenv install --list     || true
  
