os:
  - linux
  #- osx
  #- windows
# jobs:
language:  # https://docs.travis-ci.com/user/languages
  - android
  - c
  - csharp
  - cpp
  - clojure
  - crystal
  - d
  - dart
  - elixir
  - elm
  - erlang
  - generic
  - go
  - groovy
  - haskell
  - haxe
  - java
  - julia
  - minimal
  - nix
  - nodejs
  - objective-c
  - perl
  - perl6
  - php
  - python
  - r
  - ruby
  - rust
  - scala
  - smalltalk
  - swift

install: true
script:
  - python         --version || true
  - python2        --version || true
  - python3        --version || true
  - python  -m pip --version || true
  - python2 -m pip --version || true
  - python3 -m pip --version || true
  - pyenv version            || true
  - pyenv whence python3     || true
  - pyenv whence pip         || true
  - pyenv versions           || true
  
