os:
  - linux
  #- osx
  #- windows
jobs:
  include:  # https://docs.travis-ci.com/user/languages
    - language: android
    - language: c
    - language: csharp
    - language: cpp
    - language: clojure
    - language: crystal
    - language: d
    - language: dart
    - language: elixir
    - language: elm
    - language: erlang
    - language: generic
    - language: go
    - language: groovy
    - language: haskell
    - language: haxe
    - language: java
    - language: julia
    - language: minimal
    - language: nix
    - language: nodejs
    - language: objective-c
    - language: perl
    - language: perl6
    - language: php
    - language: python
    - language: r
    - language: ruby
    - language: rust
    - language: scala
    - language: smalltalk
    # - language: swift == objective-c

install: true
script:
  - python         --version || true
  - python2        --version || true
  - python3        --version || true
  - python  -m pip --version || true
  - python2 -m pip --version || true
  - python3 -m pip --version || true
  - pyenv version            || true
  - pyenv whence python3     || true
  - pyenv whence pip         || true
  - pyenv versions           || true
  
