os:
  #- linux
  #- osx
  - windows
jobs:
  include:  # https://docs.travis-ci.com/user/languages
    - language: android
    - language: c
    - language: csharp       #                                               windows: FAILS
    - language: cpp
    - language: clojure
    - language: crystal      #                                               windows: FAILS
    - language: d            #                                               windows: FAILS
    - language: dart
    - language: elixir       #                         osx: FAILS            windows: FAILS
    - language: elm
    - language: erlang       # linux: FAILS,           osx: FAILS            windows: FAILS
    - language: generic      # linux: no language set, osx: no language set, windows: FAILS
    - language: go
    - language: groovy       # linux: no language set, osx: no language set, windows: FAILS
    - language: haskell      #                         osx: FAILS,           windows: FAILS
    - language: haxe         #                                               windows: FAILS
    - language: java         #                                               windows: FAILS
    - language: julia
    - language: minimal      # linux: no language set, osx: no language set, 
    - language: nix
    - language: nodejs       # linux: no language set, osx: no language set, 
    - language: objective-c  # linux: no language set, osx: no language set, 
    - language: perl
    - language: perl6
    - language: php          #                         osx: FAILS
    - language: python       #                         osx: FAILS
    - language: r
    - language: ruby
    - language: rust
    - language: scala
    - language: smalltalk
    #- language: swift == objective-c

install: true
script:
  - python         --version || true
  - python2        --version || true
  - python3        --version || true
  - python  -m pip --version || true
  - python2 -m pip --version || true
  - python3 -m pip --version || true
  - pyenv version            || true
  - pyenv whence python3     || true
  - pyenv whence pip         || true
  - pyenv versions           || true
  - pyenv install --list     || true
  
